class UserState:
    MAIN_MENU = "main_menu"
    CREATING_SHOP = "creating_shop"
    SHOP_MENU = "shop_menu"
    EDITING_TOKEN = "editing_token"
    EDITING_WELCOME = "editing_welcome"
    CREATING_CATEGORY = "creating_category"
    ADDING_PRODUCT = "adding_product"
    PRODUCT_NAME = "product_name"
    PRODUCT_PRICE = "product_price"
    PRODUCT_DESCRIPTION = "product_description"
    PRODUCT_IMAGE = "product_image"
    EDITING_PAYMENT = "editing_payment"
    ADDING_ADMIN = "adding_admin"
    GET_USER_ID = "get_user_id"
    EDITING_PRODUCT = "editing_product"
    WORKERS_MENU = "workers_menu"
    ADDING_WORKER = "adding_worker"
    REMOVING_WORKER = "removing_worker"
    EDITING_CATEGORY_NAME = "editing_category_name"
    DELETING_CATEGORY = "deleting_category"

class ShopBotState:
    MAIN_MENU = "main_menu"
    LEAVING_REVIEW = "leaving_review"
    REVIEW_RATING = "review_rating"
    REVIEW_TEXT = "review_text"
    VIEWING_CART = "viewing_cart"
    ENTERING_ADDRESS = "entering_address"
    EDITING_PRODUCT = "editing_product"
    BROWSE_CATEGORIES = "browse_categories"
    VIEW_PRODUCT = "view_product"
    SEARCH_MODE = "search_mode"
    FILTER_MODE = "filter_mode"
    VIEW_RECOMMENDATIONS = "view_recommendations"
    SEARCH_INPUT = "search_input"
    FILTER_MIN_PRICE = "filter_min_price"
    FILTER_MAX_PRICE = "filter_max_price"